# Generated by Django 4.2.4 on 2023-08-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_data_event_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_data',
        ),
    ]
