# Generated by Django 4.2.4 on 2023-08-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venue_email_address_alter_venue_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyWebsiteUsers',
        ),
    ]
