# Generated by Django 4.2.4 on 2023-08-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_user_mywebsiteusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyWebsiteUsers',
            new_name='MyWebsiteUser',
        ),
    ]
